[functions]
directory = "netlify/functions"

# Forward /api/<anything> to the function as /.netlify/functions/rap/<anything>
[[redirects]]
from = "/api/*"
to   = "/.netlify/functions/rap/:splat"
status = 200
