[functions]
directory = "netlify/functions"

# /api -> full object
[[redirects]]
from = "/api"
to = "/.netlify/functions/rap"
status = 200

# /api/<anything> -> single record (?name=<anything>)
[[redirects]]
from = "/api/*"
to = "/.netlify/functions/rap?name=:splat"
status = 200
